-- phase-1 exploration analysis

-- 1. Total revenue generated by the food delivery app

SELECT SUM(order_amount - discount) AS total_revenue
FROM orders;

-- 2. Total Orders Per City

SELECT r.city, COUNT(*) AS total_orders
FROM orders o
JOIN restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.city
ORDER BY total_orders DESC;

-- 3. Top 10 Customers by Spending 

SELECT c.customer_id, c.name, SUM(o.order_amount - o.discount) AS total_spent
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
GROUP BY c.customer_id, c.name
ORDER BY total_spent DESC
LIMIT 10;

-- PHASE 2 — CUSTOMER SEGMENTATION

--4. Customer Category (Gold/Silver/Bronze)

WITH customer_spending AS (
    SELECT 
        c.customer_id,
        c.name,
        SUM(o.order_amount - o.discount) AS total_spent
    FROM customers c
    JOIN orders o 
        ON c.customer_id = o.customer_id
    GROUP BY c.customer_id, c.name
)
SELECT *,
    CASE 
        WHEN total_spent >= 5000 THEN 'Gold'
        WHEN total_spent >= 2000 THEN 'Silver'
        ELSE 'Bronze'
    END AS customer_category
FROM customer_spending
ORDER BY total_spent DESC;

-- PHASE 3 — RESTAURANT PERFORMANCE

--5.Top 10 Restaurants by Revenue

SELECT r.restaurant_id,r.restaurant_name,r.city, SUM(o.order_amount - o.discount) AS total_revenue
FROM restaurants r
JOIN orders o ON r.restaurant_id = o.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name, r.city
ORDER BY total_revenue DESC
LIMIT 10;

--6.Average Rating vs Revenue 

SELECT 
    r.restaurant_id,
    r.restaurant_name,
    r.rating AS avg_rating,
    SUM(o.order_amount - o.discount) AS total_revenue
FROM restaurants r
JOIN orders o 
    ON r.restaurant_id = o.restaurant_id
GROUP BY 
    r.restaurant_id,
    r.restaurant_name,
    r.rating
ORDER BY 
    total_revenue DESC;

-- PHASE 4 — DELIVERY ANALYSIS

-- 7. Average Delivery Time Per City

SELECT r.city, AVG(o.delivery_time) AS avg_delivery_time
FROM orders o
JOIN restaurants r ON o.restaurant_id = r.restaurant_id
WHERE o.delivery_time IS NOT NULL
GROUP BY r.city
ORDER BY avg_delivery_time DESC;

-- 8. Late Deliveries (Above 45 Minutes)

SELECT o.order_id, r.restaurant_name, o.delivery_time
FROM orders o
JOIN restaurants r ON o.restaurant_id = r.restaurant_id
WHERE o.delivery_time > 45;

-- PHASE 5 — PAYMENT & DISCOUNT ANALYSIS

-- 9.Payment Method Distribution

SELECT payment_method, COUNT(*) AS count
FROM orders
GROUP BY payment_method
ORDER BY count DESC;

-- 10. Discount Impact on Revenue
SELECT 
    CASE 
        WHEN discount > 0 THEN 'With Discount'
        ELSE 'Without Discount'
    END AS discount_status,
    SUM(order_amount - discount) AS total_revenue
FROM orders
GROUP BY discount_status;

-- PHASE 6 — ADVANCED SQL

-- 11.Monthly Revenue Using CTE

WITH monthly_revenue AS (
    SELECT 
        month(order_date) AS month,
        SUM(order_amount - discount) AS total_revenue
    FROM orders
    GROUP BY  month
)
SELECT month, total_revenue
FROM monthly_revenue
ORDER BY month;

-- 12. Rank Restaurants by Revenue (Window Function)
SELECT 
    r.restaurant_id,
    r.restaurant_name,
    SUM(o.order_amount - o.discount) AS total_revenue,
    RANK() OVER (ORDER BY SUM(o.order_amount - o.discount) DESC) AS revenue_rank
FROM restaurants r
JOIN orders o ON r.restaurant_id = o.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name
ORDER BY total_revenue DESC;

-- 13. Above Average Revenue Restaurants (Subquery)
SELECT 
    r.restaurant_id,
    r.restaurant_name,
    SUM(o.order_amount - o.discount) AS total_revenue
FROM restaurants r
JOIN orders o 
    ON r.restaurant_id = o.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name
HAVING SUM(o.order_amount - o.discount) > (
    SELECT AVG(restaurant_revenue)
    FROM (
        SELECT 
            SUM(order_amount - discount) AS restaurant_revenue
        FROM orders
        GROUP BY restaurant_id
    ) AS revenue_table
);

-- PHASE 7 — DATABASE OBJECTS

-- 14.Create Revenue View

CREATE OR REPLACE VIEW restaurant_revenue_view AS
SELECT 
    r.restaurant_id,
    r.restaurant_name,
    SUM(o.order_amount - o.discount) AS total_revenue
FROM restaurants r
JOIN orders o ON r.restaurant_id = o.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name;

-- 15. Stored Procedure: Get Top N Restaurant
CREATE PROCEDURE GetTopNRestaurants(IN top_n INT)
BEGIN
    SELECT 
        r.restaurant_id,
        r.restaurant_name,
        SUM(o.order_amount - o.discount) AS total_revenue
    FROM restaurants r
    JOIN orders o 
        ON r.restaurant_id = o.restaurant_id
    GROUP BY r.restaurant_id, r.restaurant_name
    ORDER BY total_revenue DESC
    LIMIT top_n;
END;

CALL GetTopNRestaurants(10);

-- PHASE 8-- Performance Optimization

-- 16. Index on order_date 

CREATE INDEX idx_order_date ON orders(order_date);

SHOW INDEX FROM orders WHERE Column_name = 'order_date';

-- 17. Index on customer_name 
CREATE INDEX idx_customer_name ON customers(name);

SHOW INDEX FROM customers WHERE Column_name = 'name';

-- 18. Index on restaurant_name
CREATE INDEX idx_restaurant_name ON restaurants(restaurant_name);
SHOW INDEX FROM restaurants WHERE Column_name = 'restaurant_name';

-- PHASE 9 —Automation Logic
--  Auto log high value order

CREATE TABLE high_value_orders (
    log_id INT PRIMARY KEY AUTO_INCREMENT,
    order_id INT,
    customer_id INT,
    restaurant_id INT,
    order_amount DECIMAL(10,2),
    log_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER trg_high_value_order
AFTER INSERT ON orders
FOR EACH ROW
BEGIN
    IF NEW.order_amount - NEW.discount > 1000 THEN
        INSERT INTO high_value_orders_log (order_id, customer_id, restaurant_id, order_amount)
        VALUES (NEW.order_id, NEW.customer_id, NEW.restaurant_id, NEW.order_amount - NEW.discount);
    END IF;
END;

-- 19. Create trigger to Prevent Negative Discount

CREATE TRIGGER trg_prevent_negative_discount
BEFORE INSERT ON orders
FOR EACH ROW
BEGIN
    IF NEW.discount < 0 THEN
        SET NEW.discount = 0;
    END IF;
END;

INSERT INTO orders VALUES (1014, 231, 138, '2024-01-01 12:00:00', 500.00, -20.00, 'Credit Card', 30);

SELECT * FROM orders WHERE order_id = 1014; -- Verify that discount is set to 0 and not negative

-- 20. Delivery Delay Warning

CREATE TABLE delivery_delay_warnings (
    log_id INT PRIMARY KEY AUTO_INCREMENT,
    order_id INT,
    restaurant_id INT,
    delivery_time INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER log_late_delivery
AFTER INSERT  ON orders
FOR EACH ROW
BEGIN
    IF NEW.delivery_time > 45 THEN
        INSERT INTO delivery_delay_warnings (order_id, restaurant_id, delivery_time)
        VALUES (NEW.order_id, NEW.restaurant_id, NEW.delivery_time);
    END IF;
END;

INSERT INTO orders VALUES (1015, 232, 138, '2024-01-02 13:00:00', 600.00, 90.00, 'Cash', 55);